#' Import raw calcium imaging data
#'
#' Read raw calcium imaging fluorescence traces from a CSV file.
#'
#' @param file Path to the raw CSV file.
#'
#' @return A list containing:
#' \describe{
#'   \item{frame}{Frame numbers}
#'   \item{fluorescence_matrix}{Raw fluorescence matrix}
#' }
#'
#' @export
import_calcium_data <- function(file) {

  raw_data <- read.csv(file, header = FALSE)

  frame <- raw_data$V1

  fluorescence_matrix <- raw_data[, 2:ncol(raw_data)]

  return(list(
    frame = frame,
    fluorescence_matrix = fluorescence_matrix
  ))
}

#' Normalize calcium traces by F0
#'
#' Perform F/F0 normalization for calcium imaging traces.
#'
#' @param fluorescence_matrix Raw fluorescence matrix.
#' @param f0_range Frame range used to calculate F0.
#'
#' @return A list containing:
#' \describe{
#'   \item{f0_values}{Calculated F0 values}
#'   \item{normalized_traces}{F/F0 normalized traces}
#' }
#'
#' @export
normalize_traces <- function(fluorescence_matrix, f0_range = 1:23) {

  f0_values <- apply(
    fluorescence_matrix[f0_range, ],
    2,
    mean,
    na.rm = TRUE
  )

  normalized_traces <- sweep(
    fluorescence_matrix,
    2,
    f0_values,
    FUN = "/"
  )

  return(list(
    f0_values = f0_values,
    normalized_traces = normalized_traces
  ))
}

#' Detect responding calcium imaging cells
#'
#' Detect responding cells based on Fmax and baseline standard deviation.
#'
#' @param normalized_traces F/F0 normalized calcium traces.
#' @param f0_values Calculated F0 values.
#' @param peak_range Frame range used to calculate Fmax.
#' @param baseline_sd_range Frame range used to calculate baseline SD.
#'
#' @return A list containing:
#' \describe{
#'   \item{cell_summary}{Summary statistics for each cell}
#'   \item{count_summary}{Counts of responding cells}
#' }
#'
#' @export
detect_responding_cells <- function(
    normalized_traces,
    f0_values,
    peak_range = 57:128,
    baseline_sd_range = 34:56
) {

  fmax_values <- apply(
    normalized_traces[peak_range, ],
    2,
    max,
    na.rm = TRUE
  )

  peak_height <- fmax_values - 1

  baseline_sd <- apply(
    normalized_traces[baseline_sd_range, ],
    2,
    sd,
    na.rm = TRUE
  )

  responding_5sd <- ifelse(fmax_values > 1 + 5 * baseline_sd, 1, 0)
  responding_7sd <- ifelse(fmax_values > 1 + 7 * baseline_sd, 1, 0)
  responding_10sd <- ifelse(fmax_values > 1 + 10 * baseline_sd, 1, 0)

  cell_summary <- data.frame(
    cell = paste0("Cell_", 1:ncol(normalized_traces)),
    F0 = f0_values,
    Fmax = fmax_values,
    peak_height = peak_height,
    baseline_sd = baseline_sd,
    responding_5sd = responding_5sd,
    responding_7sd = responding_7sd,
    responding_10sd = responding_10sd
  )

  count_summary <- data.frame(
    count_all = ncol(normalized_traces),
    count_5sd = sum(responding_5sd),
    count_7sd = sum(responding_7sd),
    count_10sd = sum(responding_10sd)
  )

  return(list(
    cell_summary = cell_summary,
    count_summary = count_summary
  ))
}

#' Summarize calcium imaging timecourse
#'
#' Calculate population mean, SD, and SEM across timepoints.
#'
#' @param normalized_traces F/F0 normalized calcium traces.
#' @param frame Frame numbers.
#' @param total_time_sec Total recording time in seconds.
#'
#' @return A dataframe containing:
#' \describe{
#'   \item{frame}{Frame numbers}
#'   \item{time_sec}{Time in seconds}
#'   \item{time_min}{Time in minutes}
#'   \item{mean_ff0}{Mean F/F0 values}
#'   \item{sd_ff0}{Standard deviation of F/F0}
#'   \item{n_cells}{Number of cells}
#'   \item{sem_ff0}{Standard error of the mean}
#' }
#'
#' @export
summarize_timecourse <- function(
    normalized_traces,
    frame,
    total_time_sec = 120
) {

  timecourse_summary <- data.frame(
    frame = frame,
    time_sec = total_time_sec * frame / max(frame),
    time_min = (total_time_sec * frame / max(frame)) / 60,
    mean_ff0 = apply(normalized_traces, 1, mean, na.rm = TRUE),
    sd_ff0 = apply(normalized_traces, 1, sd, na.rm = TRUE),
    n_cells = apply(!is.na(normalized_traces), 1, sum)
  )

  timecourse_summary$sem_ff0 <-
    timecourse_summary$sd_ff0 / sqrt(timecourse_summary$n_cells)

  return(timecourse_summary)
}


#' Plot individual calcium traces
#'
#' Generate a PDF plot showing individual F/F0 traces for all cells.
#'
#' @param normalized_traces F/F0 normalized calcium traces.
#' @param timecourse_summary Timecourse summary generated by summarize_timecourse().
#' @param output_file Output PDF file name.
#'
#' @return No return value. A PDF figure is saved to the working directory.
#'
#' @export
plot_individual_traces <- function(
    normalized_traces,
    timecourse_summary,
    output_file = "Figure1_Individual_Traces.pdf"
) {

  pdf(output_file, width = 7, height = 5)

  matplot(
    timecourse_summary$time_min,
    normalized_traces,
    type = "l",
    lty = 1,
    xlab = "Time (min)",
    ylab = "F/F0",
    main = "Individual Calcium Traces"
  )

  dev.off()
}

#' Plot mean calcium trace with SEM
#'
#' Generate a PDF plot showing mean F/F0 traces with SEM error bars.
#'
#' @param timecourse_summary Timecourse summary generated by summarize_timecourse().
#' @param output_file Output PDF file name.
#'
#' @return No return value. A PDF figure is saved to the working directory.
#'
#' @export
plot_mean_sem <- function(
    timecourse_summary,
    output_file = "Figure2_Mean_SEM.pdf"
) {

  pdf(output_file, width = 5, height = 5)

  plot(
    timecourse_summary$time_min,
    timecourse_summary$mean_ff0,
    type = "o",
    pch = 16,
    lwd = 2,

    ylim = c(
      min(timecourse_summary$mean_ff0 -
            timecourse_summary$sem_ff0),
      max(timecourse_summary$mean_ff0 +
            timecourse_summary$sem_ff0)
    ),

    xlab = "Time (min)",

    ylab = "Mean F/F0"
  )

  arrows(
    timecourse_summary$time_min,
    timecourse_summary$mean_ff0 -
      timecourse_summary$sem_ff0,
    timecourse_summary$time_min,
    timecourse_summary$mean_ff0 +
      timecourse_summary$sem_ff0,

    angle = 90,
    code = 3,
    length = 0.03
  )

  dev.off()
}

#' Run full calcium imaging analysis workflow
#'
#' Run the complete calcium imaging analysis pipeline, including
#' data import, F/F0 normalization, responding cell detection,
#' timecourse summarization, figure generation, and regression analysis.
#'
#' @param file Path to the raw CSV file.
#' @param output_prefix Prefix used for output files.
#' @param f0_range Frame range used to calculate F0.
#' @param peak_range Frame range used to calculate Fmax.
#' @param baseline_sd_range Frame range used to calculate baseline SD.
#' @param total_time_sec Total recording time in seconds.
#'
#' @return A list containing:
#' \describe{
#'   \item{normalized_traces}{F/F0 normalized traces}
#'   \item{cell_summary}{Summary statistics for each cell}
#'   \item{count_summary}{Counts of responding cells}
#'   \item{timecourse_summary}{Population timecourse statistics}
#'   \item{regression_summary}{Linear regression statistics}
#' }
#'
#' @export
run_calcium_analysis <- function(
    file,
    output_prefix = "calcium_analysis",
    f0_range = 1:23,
    peak_range = 57:128,
    baseline_sd_range = 34:56,
    total_time_sec = 120
) {

  data <- import_calcium_data(file)

  norm <- normalize_traces(
    fluorescence_matrix = data$fluorescence_matrix,
    f0_range = f0_range
  )

  resp <- detect_responding_cells(
    normalized_traces = norm$normalized_traces,
    f0_values = norm$f0_values,
    peak_range = peak_range,
    baseline_sd_range = baseline_sd_range
  )

  timecourse_summary <- summarize_timecourse(
    normalized_traces = norm$normalized_traces,
    frame = data$frame,
    total_time_sec = total_time_sec
  )

  write.csv(norm$normalized_traces,
            paste0(output_prefix, "_normalized_traces.csv"),
            row.names = FALSE)

  write.csv(resp$cell_summary,
            paste0(output_prefix, "_cell_summary.csv"),
            row.names = FALSE)

  write.csv(resp$count_summary,
            paste0(output_prefix, "_count_summary.csv"),
            row.names = FALSE)

  write.csv(timecourse_summary,
            paste0(output_prefix, "_timecourse_summary.csv"),
            row.names = FALSE)

  plot_individual_traces(
    normalized_traces = norm$normalized_traces,
    timecourse_summary = timecourse_summary,
    output_file = paste0(output_prefix, "_individual_traces.pdf")
  )

  plot_mean_sem(
    timecourse_summary = timecourse_summary,
    output_file = paste0(output_prefix, "_mean_sem.pdf")
  )

  fit <- lm(mean_ff0 ~ time_min, data = timecourse_summary)

  regression_summary <- data.frame(
    intercept = coef(fit)[1],
    slope = coef(fit)[2],
    r_squared = summary(fit)$r.squared,
    p_value = summary(fit)$coefficients[2, 4]
  )

  write.csv(regression_summary,
            paste0(output_prefix, "_linear_regression_summary.csv"),
            row.names = FALSE)

  return(list(
    normalized_traces = norm$normalized_traces,
    cell_summary = resp$cell_summary,
    count_summary = resp$count_summary,
    timecourse_summary = timecourse_summary,
    regression_summary = regression_summary
  ))
}

